name: Deploy web

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 8080:80
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change directory to 'web'
        run: cd web

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prepare metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            latest

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./web
          push: true
          tags: ghcr.io/payetonkawa-web:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER: ${{ secrets.SERVER }}
          USER: ${{ secrets.USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
          ssh -o StrictHostKeyChecking=no $USER@$SERVER << 'EOF'
            docker pull ghcr.io/${{ github.repository }}/latest
            docker stop payetonkawa-web || true
            docker rm payetonkawa-web || true
            docker run -d --name payetonkawa-web -p 8080:80 ghcr.io/${{ github.repository }}/latest
          EOF
